### PR TITLE
WIP: Get TotalPixelMatrixOriginSequence from PlanePositionSlideSequence if not present

### PR DESCRIPTION
**Pull request by igoroctaviano**
- Original issue: https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/issues/38

### CODE REVIEW

**Comment by igoroctaviano** [comment]
@hackermd this is the current solution to get the TotalPixelMatrixOriginSequence. Even though we have the TotalPixelMatrixOriginSequence, I'm getting negative coordinates when adding annotations:

```
scoord3d.js?ae01:215 Uncaught Error: coordinates of Polygon must be positive numbers
    at new Polygon (scoord3d.js?ae01:215)
    at _geometry2Scoord3d (viewer.js?182d:138)
    at _getROIFromFeature (viewer.js?182d:340)
    at Draw.eval (viewer.js?182d:969)
    at Draw.Target.dispatchEvent (Target.js?af7a:114)
    at Draw.finishDrawing (Draw.js?8817:880)
    at Draw.handleUpEvent (Draw.js?8817:574)
    at Draw.PointerInteraction.handleEvent (Pointer.js?154c:144)
    at Draw.handleEvent (Draw.js?8817:524)
    at Map.PluggableMap.handleMapBrowserEvent (PluggableMap.js?7229:860)
```
Is that what you meant in your comment [here](https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/issues/44#issuecomment-742611005)?

Maybe there is some part of the viewer that needs to be updated? 

I'm on my way to get permission to share the test data with you so you can have a better look at it.

**Comment by hackermd** [comment]
Thanks @igoroctaviano for looking into the issue. Test data would certainly be help to debug the issue.

**Comment by hackermd** [comment]
In general, I am reluctant to hack around issues due to missing type I attributes. If a required attribute is missing in a data set, it is an indication that the data set may have additional standard compliance issues.

**Comment by hackermd** [comment]
If type 1 attributes are missing that are required for image display, the viewer should refuse to display the images. I would propose to try to fix the metadata before passing them to the viewer constructor.

**Pull request closed without merging**
