### PR TITLE
Issue 51: Fix measurement calculation

### PR DESCRIPTION
**Pull request by igoroctaviano**
- Match scale line decimal

### CODE REVIEW

**Comment by hackermd** [comment]
Thanks @igoroctaviano. I am trying to test your branch locally, but am running into issues when building:

```none
$ npm run build

> dicom-microscopy-viewer@0.23.1 build
> rollup -c


src/dicom-microscopy-viewer.js → build/dicom-microscopy-viewer.js...
[!] Error: 'Decimal' is not exported by node_modules/decimal.js/decimal.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules/mathjs/es/function/arithmetic/ceil.js (13:9)
11: function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }
12:
13: import { Decimal } from 'decimal.js';
             ^
14: import { factory } from '../../utils/factory';
15: import { deepMap } from '../../utils/collection';

npm ERR! code 1
```

Did you run into this issue, too?

**Comment by igoroctaviano** [comment]
> Thanks @igoroctaviano. I am trying to test your branch locally, but am running into issues when building:
> 
> ```
> $ npm run build
> 
> > dicom-microscopy-viewer@0.23.1 build
> > rollup -c
> 
> 
> src/dicom-microscopy-viewer.js → build/dicom-microscopy-viewer.js...
> [!] Error: 'Decimal' is not exported by node_modules/decimal.js/decimal.js
> https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
> node_modules/mathjs/es/function/arithmetic/ceil.js (13:9)
> 11: function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }
> 12:
> 13: import { Decimal } from 'decimal.js';
>              ^
> 14: import { factory } from '../../utils/factory';
> 15: import { deepMap } from '../../utils/collection';
> 
> npm ERR! code 1
> ```
> 
> Did you run into this issue, too?

@hackermd hi there, it's not related to this change though, just checked out to master, and the build is broken there too. Something related to file-type which is a dependency used by image-type that was recently introduced.

**Comment by hackermd** [comment]
> The error you mentioned is mathjs related i think?

Yes, looks like. Bummer! Will need to do some digging..

**Comment by hackermd** [comment]
@igoroctaviano It turned out that we were using a relatively old version of mathjs. Upgrading the library to `9.4` resolves the issue.

**Review by hackermd — APPROVED** [review]
Thanks @igoroctaviano

**Pull request merged**
